baseURL = 'https://blog.koraia.org'
languageCode = 'ko-kr'
defaultContentLanguage = "en"
title = 'í•œêµ­ì¸ê³µì§€ëŠ¥í˜‘íšŒ ë¸”ë¡œê·¸'
theme = "dream"
enableRobotsTXT = true

[params]
description = "í•œêµ­ì¸ê³µì§€ëŠ¥í˜‘íšŒì˜ ê³µì‹ ë¸”ë¡œê·¸ì…ë‹ˆë‹¤. AI ê¸°ìˆ  ë™í–¥, ìµœì‹  íŠ¸ë Œë“œ, ê·¸ë¦¬ê³  ì¸ê³µì§€ëŠ¥ì˜ ë¯¸ë˜ì— ëŒ€í•œ ì¸ì‚¬ì´íŠ¸ë¥¼ ê³µìœ í•©ë‹ˆë‹¤."
images = ["https://file.miricanvas.com/design_thumb/2025/03/10/15/40/kqu7mcbl88r29r5c/thumb.jpg"]
lightTheme = "emerald"
darkTheme = "forest"
author = "koraia"
avatar = "img/avatar.svg"
headerTitle = "ë¯¸ë˜ë¥¼ ì—¬ëŠ” AI,"
motto = "ì‚¬ë‹¨ë²•ì¸ í•œêµ­ì¸ê³µì§€ëŠ¥í˜‘íšŒ"
footerBottomText = "ğŸŒ± ì‚¬ë‹¨ë²•ì¸ í•œêµ­ì¸ê³µì§€ëŠ¥í˜‘íšŒ"
email = "info@koraia.org"
siteStartYear = 2017
favicon = "img/symbol.ico"
collapseNavItems = ["posts", "categories", "tags"]
showTableOfContents = true
showSummaryCoverInPost = true
imageZoomableInPost = true
showPrevNextPost = true
reorderShares = ["x", "facebook"]

[params.experimental]
jsDate = true
jsDateFormat = "yyyy. MM. dd."
