baseURL = 'https://koraiablog.github.io/'
languageCode = 'ko-kr'
defaultContentLanguage = "en"
title = 'KORAIA'
theme = "dream"
enableRobotsTXT = true

[params]
images = ["https://file.miricanvas.com/design_thumb/2025/03/10/15/40/kqu7mcbl88r29r5c/thumb.jpg"]
lightTheme = "emerald"
darkTheme = "forest"
author = "koraia"
avatar = "img/avatar.svg"
headerTitle = "ë¯¸ë˜ë¥¼ ì—¬ëŠ” AI,"
motto = "ì‚¬ë‹¨ë²•ì¸ í•œêµ­ì¸ê³µì§€ëŠ¥í˜‘íšŒ"
footerBottomText = "ğŸŒ± ì‚¬ë‹¨ë²•ì¸ í•œêµ­ì¸ê³µì§€ëŠ¥í˜‘íšŒ"
email = "info@koraia.org"
siteStartYear = 2017
favicon = "symbol.ico"
collapseNavItems = ["posts", "categories", "tags"]
showTableOfContents = true
showSummaryCoverInPost = true
imageZoomableInPost = true
showPrevNextPost = true
reorderShares = ["x", "facebook"]

[params.experimental]
jsDate = true
jsDateFormat = "yyyy. MM. dd."